name: Theme CD

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version.
        type: string
        required: false
        default: "20"
      pnpm-version:
        description: pnpm version.
        type: string
        required: false
        default: "10"
      skip-appstore-release:
        description: Indicates if the appstore release should be skipped.
        type: boolean
        required: false
        default: false
      app-id:
        description: Application ID from Halo App Store.
        required: false
        type: string
        default: not-configured-app-id
      yunext-backend-baseurl:
        description: Base URL of Halo App Store.
        required: false
        default: https://yunext.cn
        type: string
    secrets:
      yunext-pat:
        description: Personal access token of Halo Appstore.
        required: false
jobs:
  package:
    name: Package Theme
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ inputs.pnpm-version }}
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: theme-package
          path: dist

  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs: package
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: theme-package
          path: dist
      - name: Upload Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} dist/*

  appstore-release:
    name: App Store Release
    runs-on: ubuntu-latest
    needs: package
    if: ${{ github.event_name == 'release' && !inputs.skip-appstore-release }}
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: theme-package
          path: dist
      - name: Release to App Store
        uses: halo-kunkunyu/app-store-release-action@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          app-id: ${{ inputs.app-id }}
          yunext-backend-baseurl: ${{ inputs.yunext-backend-baseurl }}
          release-id: ${{ github.event.release.id }}
          assets-dir: dist
          yunext-pat: ${{ secrets.yunext-pat }}
